### ISSUE TITLE
runweb should be an optional extra

### ISSUE THREAD

**Issue by ahvigil** [Mizzou-CBMI/COSMOS2#108]
The flask web application packaged with Cosmos is not really necessary for core Cosmos workflow management functionality, but flask and all its dependencies end up being installed regardless. It would be nice if the requirements for `cosmos runweb` could be included as a package extra so these only get installed if explicitly requested by the user. This would reduce the package footprint when running in a non-interactive environment while still allowing users to opt-in when desired.

**Comment by btrspg** [comment]
Yes, I agree with that.
