### ISSUE TITLE
Community suggestion

### ISSUE THREAD

**Issue by btrspg** [Mizzou-CBMI/COSMOS2#150]
Hi there,

I saw many other workflows based on other core (e.g. nextflow: https://github.com/nf-core) have their community for the collection of workflows based on certain core. 

I think COSMOS2 is a very good **Pipeline Management System**, we could also have an organism to collect pipelines that based on COSMOS2 for others easy use. 

Will you consider about this?

Best wishes,

**Comment by egafni** [comment]
Sounds great!  Would you like to lead this effort?  Happy to help if so.
