### ISSUE TITLE
Mount custom volumes to Docker image

### ISSUE THREAD

**Issue by valeandri** [Mizzou-CBMI/COSMOS2#152]
Hello COSMOS community,

I am efficiently using Cosmos with the AWS batch DRM to send my pipeline in the Cloud.

I would like to make a couple of suggestion for improvements:
- make it possible to customize the volumes to mount on the docker container
- avoid/limit the "argv" parameter in the job definition, since it causes issues when multiple argument are passed to the pipeline (the string must be shorter than 256 characters which is not that much)

If found useful, I would like to contribute implementing these improvements, also accepting suggestions from you.

Waiting from any feedback,

**Comment by egafni** [comment]
These would both be acceptable as a PR for me, feel free to post a work in progress PR first if you would like direct feed back
