### ISSUE TITLE
CWL support for COSMOS2

### ISSUE THREAD

**Issue by pvanheus** [Mizzou-CBMI/COSMOS2#45]
Following on from our chat in yesterday's H3ABionet meeting, I wonder if Cosmos could parse a CWL workflow specification and turn it into a COSMOS2 workflow. The  [Toil](https://github.com/BD2KGenomics/toil) has an example of how this could work: they re-use CWL-specified tools by invoking [cwltool](https://github.com/common-workflow-language/cwltool) to run them.

@yassineS mentioned resource requirements. This was discussed at a recent CWL on HPC working group meeting (see minutes: https://docs.google.com/document/d/1-yCGtCJLb_jRpPG8vcgIMR7jC4KDuB04ZiXcbmkpErw/edit?ts=56fd360d), hopefully that spec will move forward.

**Comment by yassineS** [comment]
Thank you @pvanheus for the nice discussion and the valuable suggestion.

@egafni I presented yesterday the work we've done so far during, the pan-African Bioinformatics Network (H3AbiNet) Cloud Computing task force. The task force is fairly new, and this point came up.

**Comment by egafni** [comment]
This really isn't on my radar as I'm generally not a fan of the concept
language-agnostic workflow languages; it's just not very practical.

p.s. doing a major release of cosmos2 very soon

**Comment by egafni** [comment]
Update:  It might be more useful to have COSMOS2 support *outputting* CWL

**Comment by egafni** [comment]
closing since CWL seems to have lost steam
